swipe:
  3:
    left:
      command: "xdotool key alt+Left" # History forward
    right:
      command: "xdotool key alt+Right" # History back
    up:
      command: "xdotool key super+Up" # Activity
    down:
      command: "xdotool key super+Down" # Activity
  4:
    left:
      command: "/home/jonalm/scripts/other/get_notifications.py"
      # command: "xdotool key ctrl+alt+Left" # Switch to next workspace
    right:
      command: "/home/jonalm/scripts/other/get_notifications.py"
      # command: "xdotool key ctrl+alt+Right" # Switch to previous workspace
    up:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    down:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
hold:
  4:
    command: "xdotool key super" # Activity
