"""awd

Revision ID: 0d3aae5fbbe3
Revises: 
Create Date: 2023-12-05 00:23:00.059353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3aae5fbbe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_children')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_children',
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('child_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], )
    )
    # ### end Alembic commands ###
