"""awd

Revision ID: 516139046411
Revises: 0d3aae5fbbe3
Create Date: 2023-12-05 00:24:01.475863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516139046411'
down_revision = '0d3aae5fbbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
